using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

namespace Yodo1.Localization
{
    public class LanguageUtils : Editor
    {
        private static Dictionary<string, List<string>> mLanguageDef = new Dictionary<string, List<string>>()
    {
            {"Abkhazian",                               new List<string>(){"ab"}},
            {"Afar",                                    new List<string>(){"aa"}},
            {"Afrikaans",                               new List<string>(){"af"}},
            {"Akan",                                    new List<string>(){"ak"}},
            {"Albanian",                                new List<string>(){"sq"}},
            {"Amharic",                                 new List<string>(){"am"}},
            {"Arabic",                                  new List<string>(){"ar"}},
            {"Arabic/Algeria",                          new List<string>(){"ar-DZ", "ar"}},
            {"Arabic/Bahrain",                          new List<string>(){"ar-BH", "ar"}},
            {"Arabic/Egypt",                            new List<string>(){"ar-EG", "ar"}},
            {"Arabic/Iraq",                             new List<string>(){"ar-IQ", "ar"}},
            {"Arabic/Jordan",                           new List<string>(){"ar-JO", "ar"}},
            {"Arabic/Kuwait",                           new List<string>(){"ar-KW", "ar"}},
            {"Arabic/Lebanon",                          new List<string>(){"ar-LB", "ar"}},
            {"Arabic/Libya",                            new List<string>(){"ar-LY", "ar"}},
            {"Arabic/Morocco",                          new List<string>(){"ar-MA", "ar"}},
            {"Arabic/Oman",                             new List<string>(){"ar-OM", "ar"}},
            {"Arabic/Qatar",                            new List<string>(){"ar-QA", "ar"}},
            {"Arabic/Saudi Arabia",                     new List<string>(){"ar-SA", "ar"}},
            {"Arabic/Syria",                            new List<string>(){"ar-SY", "ar"}},
            {"Arabic/Tunisia",                          new List<string>(){"ar-TN", "ar"}},
            {"Arabic/U.A.E.",                           new List<string>(){"ar-AE", "ar"}},
            {"Arabic/Yemen",                            new List<string>(){"ar-YE", "ar"}},
            {"Aragonese",                               new List<string>(){"an"}},
            {"Armenian",                                new List<string>(){"hy"}},
            {"Assamese",                                new List<string>(){"as"}},
            {"Avaric",                                  new List<string>(){"av"}},
            {"Avestan",                                 new List<string>(){"ae"}},
            {"Aymara",                                  new List<string>(){"ay"}},
            {"Azerbaijani",                             new List<string>(){"az"}},
            {"Bambara",                                 new List<string>(){"bm"}},
            {"Bashkir",                new List<string>(){"ba"}},
            {"Basque",              new List<string>(){"eu"}},
            {"Basque/Spain",        new List<string>(){"eu-ES", "eu"}},
            {"Belarusian",          new List<string>(){"be"}},
            {"Bengali",                new List<string>(){"bn"}},
            {"Bihari",                new List<string>(){"bh"}},
            {"Bislama",                new List<string>(){"bi"}},
            {"Bosnian",             new List<string>(){"bs"}},
            /**/{"Breton",                new List<string>(){"br"}},
            {"Bulgariaa",           new List<string>(){"bg"}},
            /**/{"Burmese",                new List<string>(){"my"}},
            {"Catalan",             new List<string>(){"ca"}},
            /**/{"Chamorro",                new List<string>(){"ch"}},
            /**/{"Chechen",                new List<string>(){"ce"}},
            /**/{"Chichewa",                new List<string>(){"ny"}},
            {"Chinese",             new List<string>(){"zh",  "zh-CN"}},
            {"Chinese/Hong Kong",   new List<string>(){"zh-HK", "zh-TW"}},
            {"Chinese/Macau",       new List<string>(){"zh-MO", "zh-CN"}},
            {"Chinese/PRC",         new List<string>(){"zh", "zh-CN"}},
            {"Chinese/Simplified",  new List<string>(){"zh", "zh-CN"}},
            {"Chinese/Singapore",   new List<string>(){"zh-SG", "zh-CN"}},
            {"Chinese/Taiwan",      new List<string>(){"zh-TW"}},
            {"Chinese/Traditional", new List<string>(){"zh-TW"}},
            /**/{"Chuvash",                new List<string>(){"cv"}},
            /**/{"Cornish",             new List<string>(){"kw"}},                                                // Check plural
            /**/{"Corsican",                new List<string>(){"co"}},
            /**/{"Cree",                new List<string>(){"cr"}},
            {"Croatian",            new List<string>(){"hr"}},
            {"Croatian/Bosnia and Herzegovina", new List<string>(){"hr-BA", "hr"}},
            {"Czech",               new List<string>(){"cs"}},
            {"Danish",              new List<string>(){"da"}},
            /**/{"Divehi",                new List<string>(){"dv"}},
            {"Dutch",               new List<string>(){"nl"}},
            {"Dutch/Belgium",       new List<string>(){"nl-BE", "nl"}},
            {"Dutch/Netherlands",   new List<string>(){"nl-NL", "nl"}},
            /**/{"Dzongkha",                new List<string>(){"dz"}},
            {"English",             new List<string>(){"en"}},
            {"English/Australia",   new List<string>(){"en-AU", "en"}},
            {"English/Belize",      new List<string>(){"en-BZ", "en"}},
            {"English/Canada",      new List<string>(){"en-CA", "en"}},
            {"English/Caribbean",   new List<string>(){"en-CB", "en"}},
            {"English/Ireland",     new List<string>(){"en-IE", "en"}},
            {"English/Jamaica",     new List<string>(){"en-JM", "en"}},
            {"English/New Zealand", new List<string>(){"en-NZ", "en"}},
            {"English/Republic of the Philippines", new List<string>(){"en-PH", "en"}},
            {"English/South Africa",new List<string>(){"en-ZA", "en"}},
            {"English/Trinidad",    new List<string>(){"en-TT", "en"}},
            {"English/United Kingdom",new List<string>(){"en-GB", "en"}},
            {"English/United States",new List<string>(){"en-US", "en"}},
            {"English/Zimbabwe",    new List<string>(){"en-ZW", "en"}},
            {"Esperanto",           new List<string>(){"eo"}},
            {"Estonian",            new List<string>(){"et"}},
            /**/{"Ewe",                new List<string>(){"ee"}},
            {"Faeroese",            new List<string>(){"fo"}},
            /**/{"Fijian",                new List<string>(){"fj"}},
            //{"Filipino", 			new List<string>(){"tl"}},
			{"Finnish",             new List<string>(){"fi"}},
            {"French",              new List<string>(){"fr"}},
            {"French/Belgium",      new List<string>(){"fr-BE", "fr"}},
            {"French/Canada",       new List<string>(){"fr-CA", "fr"}},
            {"French/France",       new List<string>(){"fr-FR", "fr"}},
            {"French/Luxembourg",   new List<string>(){"fr-LU", "fr"}},
            {"French/Principality of Monaco", new List<string>(){"fr-MC", "fr"}},
            {"French/Switzerland",  new List<string>(){"fr-CH", "fr"}},
            /**/{"Fulah",                new List<string>(){"ff"}},
            {"Galician",            new List<string>(){"gl"}},
            {"Galician/Spain",      new List<string>(){"gl-ES", "gl"}},
            {"Georgian",            new List<string>(){"ka"}},
            {"German",              new List<string>(){"de"}},
            {"German/Austria",      new List<string>(){"de-AT", "de"}},
            {"German/Germany",      new List<string>(){"de-DE", "de"}},
            {"German/Liechtenstein",new List<string>(){"de-LI", "de"}},
            {"German/Luxembourg",   new List<string>(){"de-LU", "de"}},
            {"German/Switzerland",  new List<string>(){"de-CH", "de"}},
            {"Greek",               new List<string>(){"el"}},
            /**/{"Guaraní",                new List<string>(){"gn"}},
            {"Gujarati",            new List<string>(){"gu"}},
            /**/{"Haitian",                new List<string>(){"ht"}},
            /**/{"Hausa",                new List<string>(){"ha"}},
            {"Hebrew",              new List<string>(){"he", "iw"}},
            /**/{"Herero",                new List<string>(){"hz"}},
            {"Hindi",               new List<string>(){"hi"}},
            /**/{"Hiri Motu",                new List<string>(){"ho"}},
            {"Hungarian",           new List<string>(){"hu"}},
            /**/{"Interlingua",                new List<string>(){"ia"}},
            {"Indonesian",          new List<string>(){"id"}},
            /**/{"Interlingue",                new List<string>(){"ie"}},
            {"Irish",               new List<string>(){"ga"}},
            /**/{"Igbo",                new List<string>(){"ig"}},
            /**/{"Inupiaq",                new List<string>(){"ik"}},
            /**/{"Ido",                new List<string>(){"io"}},
            {"Icelandic",           new List<string>(){"is"}},
            {"Italian",             new List<string>(){"it"}},
            {"Italian/Italy",       new List<string>(){"it-IT", "it"}},
            {"Italian/Switzerland", new List<string>(){"it-CH", "it"}},
            /**/{"Inuktitut",                new List<string>(){"iu"}},
            {"Japanese",            new List<string>(){"ja"}},
            /**/{"Javanese",                new List<string>(){"jv"}},
            /**/{"Kalaallisut",                new List<string>(){"kl"}},
            {"Kannada",             new List<string>(){"kn"}},
            /**/{"Kanuri",                new List<string>(){"kr"}},
            /**/{"Kashmiri",                new List<string>(){"ks"}},
            {"Kazakh",              new List<string>(){"kk"}},
            /**/{"Central Khmer",                new List<string>(){"km"}},
            /**/{"Kikuyu",                new List<string>(){"ki"}},
            /**/{"Kinyarwanda",                new List<string>(){"rw"}},
            /**/{"Kirghiz",                new List<string>(){"ky"}},
            /**/{"Komi",                new List<string>(){"kv"}},
            /**/{"Kongo",                new List<string>(){"kg"}},
            {"Korean",              new List<string>(){"ko"}},
            {"Kurdish",             new List<string>(){"ku"}},
			/**/{"Kuanyama",                new List<string>(){"kj"}},
            {"Latin",               new List<string>(){"la"}},
            /**/{"Luxembourgish",                new List<string>(){"lb"}},
            /**/{"Ganda",                new List<string>(){"lg"}},
            /**/{"Limburgan",                new List<string>(){"li"}},
            /**/{"Lingala",                new List<string>(){"ln"}},
            /**/{"Lao",                new List<string>(){"lo"}},
            {"Latvian",             new List<string>(){"lv"}},
            /**/{"Luba-Katanga",                new List<string>(){"lu"}},
            {"Lithuanian",          new List<string>(){"lt"}},
            /**/{"Manx",                new List<string>(){"gv"}},
            {"Macedonian",          new List<string>(){"mk"}},
            /**/{"Malagasy",                new List<string>(){"mg"}},
            {"Malay",               new List<string>(){"ms"}},
            {"Malay/Brunei Darussalam", new List<string>(){"ms-BN", "ms"}},
            {"Malay/Malaysia",      new List<string>(){"ms-MY", "ms"}},
            {"Malayalam",           new List<string>(){"ml"}},
            {"Maltese",             new List<string>(){"mt"}},
            {"Maori",               new List<string>(){"mi"}},
            {"Marathi",             new List<string>(){"mr"}},
            /**/{"Marshallese",                new List<string>(){"mh"}},
            {"Mongolian",           new List<string>(){"mn"}},
            /**/{"Nauru",                new List<string>(){"na"}},
            /**/{"Navajo",                new List<string>(){"nv"}},
            /**/{"North Ndebele",                new List<string>(){"nd"}},
            /**/{"Nepali",                new List<string>(){"ne"}},
            /**/{"Ndonga",                new List<string>(){"ng"}},
            {"Northern Sotho",      new List<string>(){"ns", "st"}},
            {"Norwegian",           new List<string>(){"nb", "no"}},
            {"Norwegian/Nynorsk",   new List<string>(){"nn", "no"}},
            /**/{"Sichuan Yi",                new List<string>(){"ii"}},
            /**/{"South Ndebele",                new List<string>(){"nr"}},
            /**/{"Occitan",                new List<string>(){"oc"}},
            /**/{"Ojibwa",                new List<string>(){"oj"}},
            /**/{"Church Slavic",                new List<string>(){"cu"}},
            /**/{"Oromo",                new List<string>(){"om"}},
            /**/{"Oriya",                new List<string>(){"or"}},
            /**/{"Ossetian",                new List<string>(){"os"}},
            /**/{"Pali",                new List<string>(){"pi"}},
            {"Pashto",              new List<string>(){"ps"}},
            {"Persian",             new List<string>(){"fa"}},
            {"Polish",              new List<string>(){"pl"}},
            {"Portuguese",          new List<string>(){"pt"}},
            {"Portuguese/Brazil",   new List<string>(){"pt-BR", "pt"}},
            {"Portuguese/Portugal", new List<string>(){"pt-PT", "pt"}},
            {"Punjabi",             new List<string>(){"pa"}},
            {"Quechua",             new List<string>(){"qu"}},
            {"Quechua/Bolivia",     new List<string>(){"qu-BO"}},
            {"Quechua/Ecuador",     new List<string>(){"qu-EC"}},
            {"Quechua/Peru",        new List<string>(){"qu-PE"}},
            {"Rhaeto-Romanic",      new List<string>(){"rm", "ro"}},
            {"Romanian",            new List<string>(){"ro"}},
            /**/{"Rundi",                new List<string>(){"rn"}},
            {"Russian",             new List<string>(){"ru"}},
            {"Russian/Republic of Moldova", new List<string>(){"ru-MO", "ru"}},
            /**/{"Sanskrit",                new List<string>(){"sa"}},
            /**/{"Sardinian",                new List<string>(){"sc"}},
            /**/{"Sindhi",                new List<string>(){"sd"}},
            /**/{"Northern Sami",                new List<string>(){"se"}},
            /**/{"Samoan",                new List<string>(){"sm"}},
            /**/{"Sango",                new List<string>(){"sg"}},
            {"Serbian",             new List<string>(){"sr"}},
            {"Serbian/Bosnia and Herzegovina",  new List<string>(){"sr-BA", "sr"}},
            {"Serbian/Serbia and Montenegro",   new List<string>(){"sr-SP", "sr"}},
            /**/{"Scottish Gaelic",                new List<string>(){"gd"}},
            /**/{"Shona",                new List<string>(){"sn"}},
            /**/{"Sinhala",                new List<string>(){"si"}},
            {"Slovak",              new List<string>(){"sk"}},
            {"Slovenian",           new List<string>(){"sl"}},
            /**/{"Somali",                new List<string>(){"so"}},
            /**/{"Southern Sotho",                new List<string>(){"st"}},
            {"Spanish",             new List<string>(){"es"}},
            {"Spanish/Argentina",   new List<string>(){"es-AR", "es"}},
            {"Spanish/Bolivia",     new List<string>(){"es-BO", "es"}},
            {"Spanish/Castilian",   new List<string>(){"es-ES", "es"}},
            {"Spanish/Chile",       new List<string>(){"es-CL", "es"}},
            {"Spanish/Colombia",    new List<string>(){"es-CO", "es"}},
            {"Spanish/Costa Rica",  new List<string>(){"es-CR", "es"}},
            {"Spanish/Dominican Republic", new List<string>(){"es-DO", "es"}},
            {"Spanish/Ecuador",     new List<string>(){"es-EC", "es"}},
            {"Spanish/El Salvador", new List<string>(){"es-SV", "es"}},
            {"Spanish/Guatemala",   new List<string>(){"es-GT", "es"}},
            {"Spanish/Honduras",    new List<string>(){"es-HN", "es"}},
            {"Spanish/Mexico",      new List<string>(){"es-MX", "es"}},
            {"Spanish/Nicaragua",   new List<string>(){"es-NI", "es"}},
            {"Spanish/Panama",      new List<string>(){"es-PA", "es"}},
            {"Spanish/Paraguay",    new List<string>(){"es-PY", "es"}},
            {"Spanish/Peru",        new List<string>(){"es-PE", "es"}},
            {"Spanish/Puerto Rico", new List<string>(){"es-PR", "es"}},
            {"Spanish/Spain",       new List<string>(){"es-ES", "es"}},
            {"Spanish/Uruguay",     new List<string>(){"es-UY", "es"}},
            {"Spanish/Venezuela",   new List<string>(){"es-VE", "es"}},
            {"Spanish/Latin Americas",   new List<string>(){"es-US", "es"}},
            /**/{"Sundanese",                new List<string>(){"su"}},
            {"Swahili",             new List<string>(){"sw"}},
            /**/{"Swati",                new List<string>(){"ss"}},
            {"Swedish",             new List<string>(){"sv"}},
            {"Swedish/Finland",     new List<string>(){"sv-FI", "sv"}},
            {"Swedish/Sweden",      new List<string>(){"sv-SE", "sv"}},
            {"Tamil",               new List<string>(){"ta"}},
            {"Tatar",               new List<string>(){"tt"}},
            {"Telugu",              new List<string>(){"te"}},
            /**/{"Tajik",                new List<string>(){"tg"}},
            {"Thai",                new List<string>(){"th"}},
            /**/{"Tigrinya",                new List<string>(){"ti"}},
            /**/{"Tibetan",                new List<string>(){"bo"}},
            /**/{"Turkmen",                new List<string>(){"tk"}},
            /**/{"Tagalog",                new List<string>(){"tl"}},
            /**/{"Tswana",                new List<string>(){"tn"}},
            /**/{"Tonga",                new List<string>(){"to"}},
            {"Turkish",             new List<string>(){"tr"}},
            /**/{"Tsonga",                new List<string>(){"ts"}},
            /**/{"Twi",                new List<string>(){"tw"}},
            /**/{"Tahitian",                new List<string>(){"ty"}},
            /**/{"Uighur",                new List<string>(){"ug"}},
            {"Ukrainian",           new List<string>(){"uk"}},
            {"Urdu",                new List<string>(){"ur"}},
            {"Uzbek",               new List<string>(){"uz"}},
            /**/{"Venda",                new List<string>(){"ve"}},
            {"Vietnamese",          new List<string>(){"vi"}},
            /**/{"Volapük",                new List<string>(){"vo"}},
            /**/{"Walloon",                new List<string>(){"wa"}},
            {"Welsh",               new List<string>(){"cy"}},
            /**/{"Wolof",                new List<string>(){"wo"}},
            /**/{"Frisian",                new List<string>(){"fy"}},
            {"Xhosa",               new List<string>(){"xh"}},
            {"Yiddish",             new List<string>(){"yi"}},
            /**/{"Yoruba",                new List<string>(){"yo"}},
            /**/{"Zhuang",                new List<string>(){"za"}},
            {"Zulu",                new List<string>(){"zu"}}
    };

        private static List<string> sDefaultList = new List<string>() { "en" };
        public static List<string> GetLanguageCode(string language)
        {
            if (string.IsNullOrEmpty(language) || mLanguageDef.ContainsKey(language) == false)
            {
                return sDefaultList;
            }

            return mLanguageDef[language];
        }

        public static List<string> GetLanguageCodes(string language)
        {
            List<string> result = new List<string>();
            //Chinese (Simplified)
            language = language.Replace(" ", "");
            language = language.Replace(")", "");
            language = language.Replace("(", "/");

            if (mLanguageDef.ContainsKey(language) == false)
            {
                return sDefaultList;
            }
            return mLanguageDef[language];
        }
    }
}
